envinfo:
  #浏览器驱动
  browserDriver: D:/python/pageAutoTest/chromeDriver/chromedriver.exe
  #url
  url: http://192.168.1.3:8080
  #数据库
  db:
    qj: 192.168.1.247:1521/tzkjk
    dj: 192.168.1.247:1521/tzdj
  #登录用户
  loginUser:
    user: zcy
    passwd: 123456